# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W94n1Czj4VQMZpr1Y120OKNpQk3P8a4B
"""

import streamlit as st
import joblib

@st.cache_data(show_spinner=True)  # Caches the model loading
def load_model():
    return joblib.load('model.joblib')

try:
    model = load_model()
except Exception as e:
    st.error(f"Failed to load model: {e}. Ensure you have trained and saved a 'model.joblib' file.")

